/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_PROTO_MESSAGE_PB_H_INCLUDED
#define PB_PROTO_PROTO_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* MsgType enumerates all WebSocket message types.
 Gate-0 SSOT: MUST include HEARTBEAT, CHAT, PRIVATE, SYSTEM, ACK, FRIEND, SIGNALING, GROUP. */
typedef enum _proto_MsgType {
    proto_MsgType_UNKNOWN = 0,
    proto_MsgType_HEARTBEAT_PING = 1, /* Client heartbeat */
    proto_MsgType_HEARTBEAT_PONG = 2, /* Server heartbeat reply */
    proto_MsgType_CHAT = 3, /* Public hall broadcast */
    proto_MsgType_PRIVATE_CHAT = 4, /* Private 1-1 chat */
    proto_MsgType_SYSTEM_NOTICE = 5, /* System global broadcast / notice */
    proto_MsgType_ACK = 6, /* Message confirmation (stanza_id + seq) */
    proto_MsgType_FRIEND_APPLY_NOTIFY = 10, /* Friend apply notification */
    proto_MsgType_FRIEND_ACCEPT_NOTIFY = 11, /* Friend accept notification */
    proto_MsgType_SIGNALING_OFFER = 20, /* WebRTC SD Offer (P2P signaling) */
    proto_MsgType_SIGNALING_ANSWER = 21, /* WebRTC SD Answer */
    proto_MsgType_SIGNALING_CANDIDATE = 22, /* ICE Candidate */
    proto_MsgType_GROUP_CHAT = 30 /* Group chat */
} proto_MsgType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(256) proto_WsMessage_payload_t;
/* WsMessage is the unified envelope for real-time and historical messages.
 Real-time WS frames and history pull use identical structure (同构同解析). */
typedef struct _proto_WsMessage {
    proto_MsgType type;
    int64_t seq; /* Monotonic per-conversation seq (server-assigned, client sends 0) */
    char from_uid[36]; /* Sender UserID (gateway forcibly overwrites) */
    char to_uid[36]; /* Receiver UserID / GroupID */
    char content[512]; /* Text content (UTF-8, no trailing \n) */
    int64_t timestamp; /* Server physical timestamp (ms) */
    proto_WsMessage_payload_t payload; /* Binary transparent payload (SDP/ICE, max 256) */
    char extra[128]; /* Extension attributes (JSON: burn TTL, media meta, max 128) */
    char stanza_id[64]; /* Client-generated dedup/ACK correlation ID (UUID, max 64) */
} proto_WsMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _proto_MsgType_MIN proto_MsgType_UNKNOWN
#define _proto_MsgType_MAX proto_MsgType_GROUP_CHAT
#define _proto_MsgType_ARRAYSIZE ((proto_MsgType)(proto_MsgType_GROUP_CHAT+1))

#define proto_WsMessage_type_ENUMTYPE proto_MsgType


/* Initializer values for message structs */
#define proto_WsMessage_init_default             {_proto_MsgType_MIN, 0, "", "", "", 0, {0, {0}}, "", ""}
#define proto_WsMessage_init_zero                {_proto_MsgType_MIN, 0, "", "", "", 0, {0, {0}}, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define proto_WsMessage_type_tag                 1
#define proto_WsMessage_seq_tag                  2
#define proto_WsMessage_from_uid_tag             3
#define proto_WsMessage_to_uid_tag               4
#define proto_WsMessage_content_tag              5
#define proto_WsMessage_timestamp_tag            6
#define proto_WsMessage_payload_tag              7
#define proto_WsMessage_extra_tag                8
#define proto_WsMessage_stanza_id_tag            9

/* Struct field encoding specification for nanopb */
#define proto_WsMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT64,    seq,               2) \
X(a, STATIC,   SINGULAR, STRING,   from_uid,          3) \
X(a, STATIC,   SINGULAR, STRING,   to_uid,            4) \
X(a, STATIC,   SINGULAR, STRING,   content,           5) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         6) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           7) \
X(a, STATIC,   SINGULAR, STRING,   extra,             8) \
X(a, STATIC,   SINGULAR, STRING,   stanza_id,         9)
#define proto_WsMessage_CALLBACK NULL
#define proto_WsMessage_DEFAULT NULL

extern const pb_msgdesc_t proto_WsMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define proto_WsMessage_fields &proto_WsMessage_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_PROTO_MESSAGE_PB_H_MAX_SIZE        proto_WsMessage_size
#define proto_WsMessage_size                     1066

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
