// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgType enumerates all WebSocket message types.
// Gate-0 SSOT: MUST include HEARTBEAT, CHAT, PRIVATE, SYSTEM, ACK, FRIEND, SIGNALING, GROUP.
type MsgType int32

const (
	MsgType_UNKNOWN              MsgType = 0
	MsgType_HEARTBEAT_PING       MsgType = 1  // Client heartbeat
	MsgType_HEARTBEAT_PONG       MsgType = 2  // Server heartbeat reply
	MsgType_CHAT                 MsgType = 3  // Public hall broadcast
	MsgType_PRIVATE_CHAT         MsgType = 4  // Private 1-1 chat
	MsgType_SYSTEM_NOTICE        MsgType = 5  // System global broadcast / notice
	MsgType_ACK                  MsgType = 6  // Message confirmation (stanza_id + seq)
	MsgType_FRIEND_APPLY_NOTIFY  MsgType = 10 // Friend apply notification
	MsgType_FRIEND_ACCEPT_NOTIFY MsgType = 11 // Friend accept notification
	MsgType_SIGNALING_OFFER      MsgType = 20 // WebRTC SD Offer (P2P signaling)
	MsgType_SIGNALING_ANSWER     MsgType = 21 // WebRTC SD Answer
	MsgType_SIGNALING_CANDIDATE  MsgType = 22 // ICE Candidate
	MsgType_GROUP_CHAT           MsgType = 30 // Group chat
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "HEARTBEAT_PING",
		2:  "HEARTBEAT_PONG",
		3:  "CHAT",
		4:  "PRIVATE_CHAT",
		5:  "SYSTEM_NOTICE",
		6:  "ACK",
		10: "FRIEND_APPLY_NOTIFY",
		11: "FRIEND_ACCEPT_NOTIFY",
		20: "SIGNALING_OFFER",
		21: "SIGNALING_ANSWER",
		22: "SIGNALING_CANDIDATE",
		30: "GROUP_CHAT",
	}
	MsgType_value = map[string]int32{
		"UNKNOWN":              0,
		"HEARTBEAT_PING":       1,
		"HEARTBEAT_PONG":       2,
		"CHAT":                 3,
		"PRIVATE_CHAT":         4,
		"SYSTEM_NOTICE":        5,
		"ACK":                  6,
		"FRIEND_APPLY_NOTIFY":  10,
		"FRIEND_ACCEPT_NOTIFY": 11,
		"SIGNALING_OFFER":      20,
		"SIGNALING_ANSWER":     21,
		"SIGNALING_CANDIDATE":  22,
		"GROUP_CHAT":           30,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

// WsMessage is the unified envelope for real-time and historical messages.
// Real-time WS frames and history pull use identical structure (同构同解析).
type WsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MsgType" json:"type,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                          // Monotonic per-conversation seq (server-assigned, client sends 0)
	FromUid       string                 `protobuf:"bytes,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`    // Sender UserID (gateway forcibly overwrites)
	ToUid         string                 `protobuf:"bytes,4,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`          // Receiver UserID / GroupID
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                   // Text content (UTF-8, no trailing \n)
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Server physical timestamp (ms)
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                   // Binary transparent payload (SDP/ICE, max 256)
	Extra         string                 `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                       // Extension attributes (JSON: burn TTL, media meta, max 128)
	StanzaId      string                 `protobuf:"bytes,9,opt,name=stanza_id,json=stanzaId,proto3" json:"stanza_id,omitempty"` // Client-generated dedup/ACK correlation ID (UUID, max 64)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *WsMessage) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_UNKNOWN
}

func (x *WsMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WsMessage) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *WsMessage) GetToUid() string {
	if x != nil {
		return x.ToUid
	}
	return ""
}

func (x *WsMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WsMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsMessage) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *WsMessage) GetStanzaId() string {
	if x != nil {
		return x.StanzaId
	}
	return ""
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x05proto\"\xf8\x01\n" +
	"\tWsMessage\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.proto.MsgTypeR\x04type\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x19\n" +
	"\bfrom_uid\x18\x03 \x01(\tR\afromUid\x12\x15\n" +
	"\x06to_uid\x18\x04 \x01(\tR\x05toUid\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x14\n" +
	"\x05extra\x18\b \x01(\tR\x05extra\x12\x1b\n" +
	"\tstanza_id\x18\t \x01(\tR\bstanzaId*\xfd\x01\n" +
	"\aMsgType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEARTBEAT_PING\x10\x01\x12\x12\n" +
	"\x0eHEARTBEAT_PONG\x10\x02\x12\b\n" +
	"\x04CHAT\x10\x03\x12\x10\n" +
	"\fPRIVATE_CHAT\x10\x04\x12\x11\n" +
	"\rSYSTEM_NOTICE\x10\x05\x12\a\n" +
	"\x03ACK\x10\x06\x12\x17\n" +
	"\x13FRIEND_APPLY_NOTIFY\x10\n" +
	"\x12\x18\n" +
	"\x14FRIEND_ACCEPT_NOTIFY\x10\v\x12\x13\n" +
	"\x0fSIGNALING_OFFER\x10\x14\x12\x14\n" +
	"\x10SIGNALING_ANSWER\x10\x15\x12\x17\n" +
	"\x13SIGNALING_CANDIDATE\x10\x16\x12\x0e\n" +
	"\n" +
	"GROUP_CHAT\x10\x1eB\tZ\a./protob\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_message_proto_goTypes = []any{
	(MsgType)(0),      // 0: proto.MsgType
	(*WsMessage)(nil), // 1: proto.WsMessage
}
var file_proto_message_proto_depIdxs = []int32{
	0, // 0: proto.WsMessage.type:type_name -> proto.MsgType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		EnumInfos:         file_proto_message_proto_enumTypes,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
